name: qr_code
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.0
  path: ^1.9.1
  qr_flutter: ^4.1.0
  sqflite: ^2.3.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true